### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by binarious** [i-m-c/jenkins-inheritance-plugin#49]
Or is it already dead? The last commit is very old and recent PRs don't get attention.
Are there any maintained forks?
Thanks

**Comment by HedAurabesh** [comment]
Hi Binarious.
Main developer of this plugin speaking.

Yes, the project is still maintained, and we're working on publishing a version 2.0 soon, which upgrades the entire source code to our internal version that has been worked on for the past 2 years since the last commit was uploaded.

These past two years have been extremely busy and filled with challenges for us, which meant that an Open Source release of the changes had to take a backseat.

Hopefully, we will be able to push out v2.0 before the end of February.

That new version should be mostly backward compatible to the previous versions, but there might be the occasional hiccough due to the sheer distance in time between the releases. Sorry about that.


Regards,
Martin Schröder

**Comment by binarious** [comment]
@HedAurabesh :+1: thank you for letting us know and also thanks a lot for your hard work!
