### ISSUE TITLE
Old incompatibilities fixed in 2.0.0 ?

### ISSUE THREAD

**Issue by HaraldNordgren** [i-m-c/jenkins-inheritance-plugin#50]
I saw the commit for version 2.0.0 (734353f227d3299fa87e3a1e1f16ab5d786d081b). Very cool and definitely a long awaited update!

Looking at the Jenkins wiki page for the old version of the plugin (https://wiki.jenkins-ci.org/display/JENKINS/inheritance-plugin) there are mentions of incompatibilities with other plugins

* Job Config History plugin
* Artifactory plugin
* Rebuilder plugin
* Various SCM plugins
* Jenkins itself

Have all of these issues been fixed?

**Comment by HedAurabesh** [comment]
Hi Harald.

- Job Config History plugin will work with this plugin, as long as you do not attempt to restore data (in which case the behaviour is undefined). The Inheritance plugin anyway contains a more complete implementation, as it allows you to switch between versions, instead of just restoring them.

- Artifactory plugin compatibility has been fixed on our end. As long as you use a newer version of the Artifactory plugin, most features of it should work. Older versions simply did not consider the InheritanceProject to be a valid project type for Artifactory. Newer versions no longer have that restriction.

- The Rebuilder plugin is now a mandatory dependency (as noted in the commit message) and should work. Do note, though, that the inheritance plugin overrides the rebuilding of jobs almost entirely in favour of its own implementation.

 - All SCM plugins tested by us should work normally. (SVN, Git, ClearCase, to be precise)

- We have not yet tested compatibility with the new UI of Jenkins 2.x. The back-end should work fine due to the relative stability of the Jenkins API, but it is possible that the UI layout will look wonky on some pages.

Regards,
Martin.
